### PR TITLE
Add wiki images

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by nohal** [comment]
Rick...
Thanks, but not like this. I do not want this stuff in the code repository.

**Comment by rgleason** [comment]
What? -- Why not? so you're using my repos...! That does not seem fair. What's the disadvantage?  I have noticed aversion to image files, data files, certain already compiled dll's, exe and stuff like that, not putting the correct opencpn.lib in a plugin /build directory, not adding data and dll that are needed to the /buildwin folder.  

At first it seemed odd because it causes people extra work who are trying to compile etc, but there must be a good reason...I just don't know what the reason is...?  Would you please explain?

So you don't want the completed wiki pages either?

**Comment by nohal** [comment]
Rick...
The images belong to the wiki, not to the code repository.

**Comment by rgleason** [comment]
Sorry but I am still learning. Tried to get it up to my github repos after a push from local.
Need to figure this step out.

**Pull request closed without merging**
